### ISSUE TITLE
Alternative 'tp_info' format using CRIs

### ISSUE THREAD

**Issue by marco-tiloca-sics** [core-wg/observe-multicast-notifications#5]
We can consider an alternative tp_info as

```
    [
       // in absolute form, with no path or query
       CORI (tp_id, srv_host, ?srv_port),
       token,
       // in authority-only form, equivalent to a `//host:port` URI reference
       CORI (cl_host, ?cl_port)
    ]
```

For consistency, entries in the new Registry "CoAP Transport Information" will have to cross-reference the "Scheme Registry" or anything else suitable for CRIs (see below, including changes to the current registry format).

 ``` 
  +-----------+-------------+--------------+-----------+
  | Scheme    | Description | Req Info     | Reference |
  | (with CRI)|             |              |           |
  +-----------+-------------+--------------+-----------+
  | coap      | UDP is used |  token       | [This     |
  | (-1)      | as per      |  cli (a rel. | document] |
  |           | RFC7252     |     CRI //x) |           |
  +-----------+-------------+--------------+-----------+
  ```
  
  * value: replaced with scheme name or what's in the CRI shorthands
  * srv addr is always a CRI (so no need to have it in the registry), with scheme and authority with empty path and no query or fragment
  * cli is a CRI reference, as used is of shape `//authority`

**Comment by chrysn** [comment]
I think CRIs are stable enough to use.

**Comment by marco-tiloca-sics** [comment]
Closed by https://github.com/core-wg/observe-multicast-notifications/pull/14/
