### ISSUE TITLE
OSCORE-binding of phantom cancellation request and cancellation response

### ISSUE THREAD

**Issue by marco-tiloca-sics** [core-wg/observe-multicast-notifications#6]
Section 7.2.4 defines how the server cancels a group observation, when Group OSCORE is used.

The server sends to itself a protected phantom cancellation request, and then sends the protected 5.03 cancellation response over multicast. What happens then?

* The cancellation response still matches with the Token of the phantom *registration* request stored by the clients (i.e., the same Token used in the phantom *cancellation* request), which is good.

* Through the external_aad, the cancellation response can cryptographically match only with the phantom *cancellation* request, that the clients have however never seen and will never see.

Thus, when receiving the cancellation response, there will be a successful CoAP-matching but not a successful OSCORE-matching at the clients, which results in a failed decryption.

Possible way out: when the server protects the cancellation response, the request_piv in the external_aad can be not the Partial IV of the phantom *cancellation* request (as it should normally be), but rather the Partial IV of the original phantom *registration* request.

The cancellation response would be protected "as if it was a group notification", but of course it still does not include an inner Observe option.

The clients will get a response with outer code 2.05 anyway, thus initially believing it to be a notification to match with the phantom registration request. After decryption, the clients can rely on the inner code 5.03 to understand that this is actually about cancelling the group observation.

**Comment by chrysn** [comment]
I think it's easier if the cancellation is just server-initiated. That'd even look 1:1 like the fix you proposed, just with an easier explanation.

**Comment by marco-tiloca-sics** [comment]
Followed the proposed simpler way as per the commit above.
