### ISSUE TITLE
Signaling of self-managed OSCORE group

### ISSUE THREAD

**Issue by marco-tiloca-sics** [core-wg/observe-multicast-notifications#9]
The appendix "OSCORE Group Self-Managed by the Server" needs to be aligned with the latest updates in core-oscore-groupcomm-12 and expected related updates in ace-key-groupcomm-oscore.

Expected additions/changes include:

* New parameters to enforce proof-of-possession of the Server's private key, here acting also as Group Manager. These should be a server-generated nonce and a signature over that nonce.
* The Server's public key in 'srv_pub_key' is in its native format used for its distribution/retrieval; the format is indicated in 'cs_key_enc' by a value from the COSE Headers Parameters registry (i.e., CWT, set of CWT claims, X.509/C509 certificates, ...); 'srv_identifier' is always present and specifying the Sender ID of the Server.
* Names and occurrence of parameters related to algorithms need to reflect the latest format of the Security Context for Group OSCORE. Some parameters are not needed anymore, since the related information would be part of the Server's public key in 'srv_pub_key'.
* The same Server's public key is used as public key of the Group Manager and as public key of the sender of phantom registration/cancellation request and multicast notifications. That is, that same public key has to be used in the elements 'sender_public_key' and 'gm_public_key' of the external_aad of those messages.

**Comment by chrysn** [comment]
as for PoP, I'd need to understand what that PoP is originally needed for.

**Comment by marco-tiloca-sics** [comment]
The updated appendix addresses all points now.

As discussed, the PoP does not require an explicit piece of evidence in the informative response, but it rather comes later on with every signed multicast notification.
